export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const ACTIVATE_CREATE_POST_MODAL = 'ACTIVATE_CREATE_POST_MODAL';
export const DEACTIVATE_CREATE_POST_MODAL = 'DEACTIVATE_CREATE_POST_MODAL';