// User action types
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const KEEP = 'KEEP';

// Post action types
export const CREATE_POST = 'CREATE_POST';
export const GET_MY_POSTS = 'GET_MY_POSTS';

// Community action types
export const CREATE_NEW_COMMUNITY = 'CREATE_NEW_COMMUNITY';
export const GET_LATEST_COMMUNITIES = 'GET_LATEST_COMMUNITIES';
export const GET_JOINED_COMMUNITIES = 'GET_JOINED_COMMUNITIES';
export const GET_ONE_COMMUNITY = 'GET_ONE_COMMUNITY';
export const GET_COMMUNITY_POSTS = 'GET_COMMUNITY_POSTS';
export const JOIN_COMMUNITY = 'JOIN_COMMUNITY'; 


// Post modal types
export const ACTIVATE_CREATE_POST_MODAL = 'ACTIVATE_CREATE_POST_MODAL';
export const DEACTIVATE_CREATE_POST_MODAL = 'DEACTIVATE_CREATE_POST_MODAL';

// Community modal types
export const ACTIVATE_CREATE_COMMUNITY_MODAL = 'ACTIVATE_CREATE_COMMUNITY_MODAL';
export const DEACTIVATE_CREATE_COMMUNITY_MODAL = 'DEACTIVATE_CREATE_COMMUNITY_MODAL';